const arrayProdutos = [
  {
    id: "1",
    nome: "Picanha",
    preco: 25.99,
    quantidade: 50,
    foto: "../../assets/images/imagensProdutos/picanha.jpg",
    categoria: "Carnes",
    mercado_id: "1",
    descricao: "Picanha de alta qualidade",
    destaque: "Não",
  },
  {
    id: "2",
    nome: "Alcatra",
    preco: 18.99,
    quantidade: 30,
    foto: "../../images/imagensProdutos/alcatra.webp",
    categoria: "Carnes",
    mercado_id: "1",
    descricao: "Alcatra macia e suculenta",
    destaque: "Não",
  },
  {
    id: "3",
    nome: "Leite Integral",
    preco: 4.99,
    quantidade: 100,
    foto: "../../images/imagensProdutos/leiteIntegral.jpg",
    categoria: "Laticínios",
    mercado_id: "1",
    descricao: "Leite fresco e nutritivo",
    destaque: "Não",
  },
  {
    id: "4",
    nome: "Queijo Minas",
    preco: 8.99,
    quantidade: 20,
    foto: "../../images/imagensProdutos/queijoMinas.jpg",
    categoria: "Laticínios",
    mercado_id: "1",
    descricao: "Queijo Minas frescal",
    destaque: "Não",
  },
  {
    id: "5",
    nome: "Bolo de Chocolate",
    preco: 15.99,
    quantidade: 10,
    foto: "../../images/imagensProdutos/boloDeChocolate.jpg",
    categoria: "Doces",
    mercado_id: "1",
    descricao: "Delicioso bolo de chocolate",
    destaque: "Não",
  },
  {
    id: "6",
    nome: "Pudim",
    preco: 12.5,
    quantidade: 15,
    foto: "../../images/imagensProdutos/pudim.jpg",
    categoria: "Doces",
    mercado_id: "1",
    descricao: "Pudim caseiro cremoso",
    destaque: "Não",
  },
  {
    id: "7",
    nome: "Peito de Frango",
    preco: 10.99,
    quantidade: 40,
    foto: "../../images/imagensProdutos/peitoDeFrango.jpg",
    categoria: "Aves",
    mercado_id: "1",
    descricao: "Peito de frango sem osso",
    destaque: "Não",
  },
  {
    id: "8",
    nome: "Coxa de Frango",
    preco: 8.5,
    quantidade: 35,
    foto: "../../images/imagensProdutos/coxaDeFrango.jpg",
    categoria: "Aves",
    mercado_id: "1",
    descricao: "Coxa de frango suculenta",
    destaque: "Não",
  },
  {
    id: "9",
    nome: "Maçãs",
    preco: 3.99,
    quantidade: 60,
    foto: "../../images/imagensProdutos/maca.jpg",
    categoria: "Hortifruti",
    mercado_id: "1",
    descricao: "Maçãs frescas e crocantes",
    destaque: "Não",
  },
  {
    id: "10",
    nome: "Bananas",
    preco: 2.5,
    quantidade: 80,
    foto: "../../images/imagensProdutos/banana.jpg",
    categoria: "Hortifruti",
    mercado_id: "1",
    descricao: "Bananas maduras e saborosas",
    destaque: "Não",
  },
  {
    id: "11",
    nome: "Queijo Prato",
    preco: 7.99,
    quantidade: 25,
    foto: "../../images/imagensProdutos/queijoPrato.jpg",
    categoria: "Queijos",
    mercado_id: "1",
    descricao: "Queijo prato fatiado",
    destaque: "Não",
  },
  {
    id: "12",
    nome: "Queijo Gorgonzola",
    preco: 11.5,
    quantidade: 15,
    foto: "../../images/imagensProdutos/queijoGorgonzola.jpg",
    categoria: "Queijos",
    mercado_id: "1",
    descricao: "Queijo gorgonzola cremoso",
    destaque: "Não",
  },
  {
    id: "13",
    nome: "Arroz Integral",
    preco: 6.99,
    quantidade: 40,
    foto: "../../images/imagensProdutos/arrozIntegral.jpg",
    categoria: "Cereais",
    mercado_id: "1",
    descricao: "Arroz integral nutritivo",
    destaque: "Não",
  },
  {
    id: "14",
    nome: "Aveia em Flocos",
    preco: 4.5,
    quantidade: 50,
    foto: "../../images/imagensProdutos/aveia.jpg",
    categoria: "Cereais",
    mercado_id: "1",
    descricao: "Aveia em flocos para o café da manhã",
    destaque: "Não",
  },
  {
    id: "15",
    nome: "Salmão",
    preco: 22.99,
    quantidade: 20,
    foto: "../../images/imagensProdutos/salmao.jpg",
    categoria: "Peixes",
    mercado_id: "1",
    descricao: "Salmão fresco e saboroso",
    destaque: "Não",
  },
  {
    id: "16",
    nome: "Atum em Lata",
    preco: 5.99,
    quantidade: 30,
    foto: "../../images/imagensProdutos/atumEmLata.jpg",
    categoria: "Peixes",
    mercado_id: "1",
    descricao: "Atum enlatado para saladas",
    destaque: "Não",
  },
  {
    id: "17",
    nome: "Espaguete",
    preco: 3.49,
    quantidade: 25,
    foto: "../../images/imagensProdutos/espaguete.jpg",
    categoria: "Massas",
    mercado_id: "1",
    descricao: "Espaguete tradicional",
    destaque: "Não",
  },
  {
    id: "18",
    nome: "Lasanha",
    preco: 9.99,
    quantidade: 10,
    foto: "../../images/imagensProdutos/lasanha.jpg",
    categoria: "Massas",
    mercado_id: "1",
    descricao: "Lasanha pronta para o forno",
    destaque: "Não",
  },
  {
    id: "19",
    nome: "Sanduíche de Frango",
    preco: 7.99,
    quantidade: 15,
    foto: "../../images/imagensProdutos/sanduicheDeFrango.jpg",
    categoria: "Lanches",
    mercado_id: "1",
    descricao: "Sanduíche de frango grelhado",
    destaque: "Não",
  },
  {
    id: "20",
    nome: "Sanduíche de Queijo",
    preco: 6.5,
    quantidade: 20,
    foto: "../../images/imagensProdutos/sanduicheDeQueijo.jpg",
    categoria: "Lanches",
    mercado_id: "1",
    descricao: "Sanduíche de queijo derretido",
    destaque: "Não",
  },
  {
    id: "21",
    nome: "Iogurte Natural",
    preco: 3.25,
    quantidade: 40,
    foto: "../../images/imagensProdutos/iorguteNatural.jpg",
    categoria: "Iorgutes",
    mercado_id: "1",
    descricao: "Iogurte natural sem adição de açúcar",
    destaque: "Não",
  },
  {
    id: "22",
    nome: "Iogurte de Morango",
    preco: 4.0,
    quantidade: 35,
    foto: "../../images/imagensProdutos/iorguteDeMorango.jpg",
    categoria: "Iorgutes",
    mercado_id: "1",
    descricao: "Iogurte sabor morango",
    destaque: "Não",
  },
  {
    id: "23",
    nome: "Refrigerante Cola",
    preco: 3.49,
    quantidade: 50,
    foto: "../../images/imagensProdutos/CocaCola.jpg",
    categoria: "Bebidas",
    mercado_id: "1",
    descricao: "Refrigerante de cola tradicional",
    destaque: "Não",
  },
  {
    id: "24",
    nome: "Suco de Laranja",
    preco: 5.99,
    quantidade: 30,
    foto: "../../images/imagensProdutos/sucoDeLaranja.jpg",
    categoria: "Bebidas",
    mercado_id: "1",
    descricao: "Suco de laranja natural",
    destaque: "Não",
  },
];

// Você pode adicionar mais produtos ou modificar os existentes conforme necessário.

export default arrayProdutos;
